### ISSUE TITLE
Trace propagation

### ISSUE THREAD

**Issue by adben** [jangaraj/keycloak-with-opentelemetry#1]
Awesome project, question? how can I propagate the trace between an application that is using OIDC for authentication in keycloak ?

**Comment by jangaraj** [comment]
Unfortunately, this is not in the scope of this project (traceability of Keycloak server). Please check https://opentelemetry.io/docs/instrumentation/

**Comment by adben** [comment]
No I'm talking about the OpenTelemetry Context Propagation, i.e. after the authorization the can be passed to the clients or database in order to have the full observability in place. just wondering if even with the OIDC or SAML interactions this can be done
